spring.application.name=eventify
spring.datasource.url=jdbc:postgresql://localhost:5432/eventify_db
spring.datasource.username=postgres
spring.datasource.password=2001
spring.jpa.hibernate.ddl-auto=update